'use client';

import React, { useState } from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Info } from 'lucide-react';

const educationContent = [
  {
    id: "apr",
    title: "What is APR?",
    content: "Annual Percentage Rate (APR) represents the yearly interest generated by your deposit. For example, a 5% APR means you'll earn 5% of your deposit over a year if rates remain constant. Unlike APY, APR doesn't account for compounding interest."
  },
  {
    id: "defi",
    title: "What is DeFi?",
    content: "Decentralized Finance (DeFi) refers to financial services that operate on blockchain networks without traditional intermediaries like banks. DeFi platforms allow you to lend, borrow, trade, and earn interest on your crypto assets in a permissionless way."
  },
  {
    id: "yield-farming",
    title: "What is Yield Farming?",
    content: "Yield farming is the practice of staking or lending crypto assets to generate returns or rewards. By depositing your tokens in DeFi protocols like Aave, you can earn interest on your holdings, similar to how a savings account works in traditional banking."
  },
  {
    id: "gas-fees",
    title: "What are Gas Fees?",
    content: "Gas fees are transaction costs paid to network validators for processing transactions on a blockchain. On Polygon, these fees are paid in MATIC tokens. Lower gas fees are one of Polygon's advantages compared to Ethereum mainnet."
  },
  {
    id: "risks",
    title: "What are the Risks?",
    content: "DeFi investments carry several risks: smart contract vulnerabilities, impermanent loss, market volatility, and protocol governance changes. Always do your research and never invest more than you can afford to lose."
  },
  {
    id: "protocols",
    title: "What are DeFi Protocols?",
    content: "DeFi protocols are decentralized applications (dApps) that provide financial services. Aave, for example, is a lending protocol where users can deposit assets to earn interest or borrow against their collateral. Each protocol has its own rules, governance, and risk profile."
  }
];

export function YieldEducation() {
  const [showEducation, setShowEducation] = useState(false);

  return (
    <div className="my-6">
      <Button 
        variant="outline" 
        onClick={() => setShowEducation(!showEducation)}
        className="flex items-center gap-2 mb-4"
      >
        <Info size={16} />
        {showEducation ? "Hide DeFi Education" : "Learn About DeFi Yields"}
      </Button>
      
      {showEducation && (
        <Card className="bg-black/20 border-gray-800">
          <CardHeader>
            <CardTitle>DeFi Yield Education</CardTitle>
            <CardDescription>
              New to DeFi? Learn the basics of yield farming and how to interpret the opportunities shown below.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Accordion type="single" collapsible className="w-full">
              {educationContent.map((item) => (
                <AccordionItem key={item.id} value={item.id}>
                  <AccordionTrigger className="text-left font-medium">
                    {item.title}
                  </AccordionTrigger>
                  <AccordionContent className="text-gray-300">
                    {item.content}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
